/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as ApiAiActionRouteImport } from './routes/api/ai/$action'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiActionRoute = ApiAiActionRouteImport.update({
  id: '/api/ai/$action',
  path: '/api/ai/$action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grammar': typeof GrammarRoute
  '/speaking': typeof SpeakingRoute
  '/api/ai/$action': typeof ApiAiActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grammar': typeof GrammarRoute
  '/speaking': typeof SpeakingRoute
  '/api/ai/$action': typeof ApiAiActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grammar': typeof GrammarRoute
  '/speaking': typeof SpeakingRoute
  '/api/ai/$action': typeof ApiAiActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/grammar' | '/speaking' | '/api/ai/$action'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/grammar' | '/speaking' | '/api/ai/$action'
  id: '__root__' | '/' | '/grammar' | '/speaking' | '/api/ai/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GrammarRoute: typeof GrammarRoute
  SpeakingRoute: typeof SpeakingRoute
  ApiAiActionRoute: typeof ApiAiActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/$action': {
      id: '/api/ai/$action'
      path: '/api/ai/$action'
      fullPath: '/api/ai/$action'
      preLoaderRoute: typeof ApiAiActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GrammarRoute: GrammarRoute,
  SpeakingRoute: SpeakingRoute,
  ApiAiActionRoute: ApiAiActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
